### PR TITLE
piku-bootstrap script for provisioning a server with piku.py

### PR DESCRIPTION
**Pull request by chr15m**
Hi @rcarmo this PR adds a new script `piku-bootstrap` which is intended to be run from the user's own machine and provisions a freshly installed remote server with piku. It basically does what is written in INSTALL.md (thanks for the comprehensive guide).

```
curl https://raw.githubusercontent.com/chr15m/piku/piku-bootstrap/piku-bootstrap > piku-bootstrap
chmod 700 piku-bootstrap
./piku-bootstrap
... sets up venv etc. ...
./piku-bootstrap my-fresh-vps-box.net
```

How it works:

 * Uses whatever Python binary the user has lying around.
 * Sets up in `~/.piku-bootstrap` on their machine. [first run only]
 * Downloads & builds virtualenv source. [first run only]
 * Gets into virtualenv.
 * Installs ansible into virtualenv. [first run only]
 * Runs embedded ansible playbook to deploy piku to the server specified.

So far tested against a Digital Ocean VPS running Ubuntu 16.04.6 x64 and it works to deploy the Python example. Would be nice to see if this runs against a fresh Raspbian or Ubuntu on Raspberry Pi.

### CODE REVIEW

**Comment by dwightmulcahy** [comment]
Nice.  I have a couple of fresh Rapbian installs laying around.  I'll give it a shot tonight to see if it works.

**Comment by rcarmo** [comment]
Looks nice. FYI, I have an old Ansible playbook here:

https://github.com/rcarmo/ansible-piku

Take a look to see if there's any useful ideas there, it's been a while.

I don't have any fresh raspbian installs I can break right now, but I'm OK with taking this in after someone can test  it 😉

**Comment by chr15m** [comment]
Quick update on this - I've been testing on my Raspberry Pi and I have some tweaks to make it run smoothly on that platform. Will push those commits when I have it working 100%.

**Comment by chr15m** [comment]
@rcarmo those playbooks have been very useful as a reference, thank you.

**Comment by chr15m** [comment]
Ok, I finally got the bootstrap script working on both remote Debian VPS and a local Raspbian device. I also fixed up the help text and made the script generally a bit more friendly.

```
$ ./piku-bootstrap

Usage: piku-bootstrap HOST [--pi] [...YOUR_ANSIBLE_ARGS...]

 HOST	Creates a user 'piku' on the machine 'HOST',
	installs git, and install the piku script there.

 --pi	Shortcut to SSH in as the user 'pi'.
	Use `ssh-copy-id pi@HOSTNAME` to upload SSH key first.

	Requires root/sudo on HOSTNAME (--pi implies sudo).
	Requires HOSTNAME to be a Debian based distribution.
```

@dwightmulcahy if you get a chance to test on any of your devices or servers let me know.

**Comment by dwightmulcahy** [comment]
I'll pull the branch later.  I should have some time to test it out.  This will be awesome!!!  :)

**Pull request merged**
